services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/output
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    entrypoint: 'python'
    command: ['app/telegram_bot.py']
    restart: unless-stopped
